apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        #image: myusername/my-flask-app:latest
        #image: registry.gitlab.com/<your-username>/<your-repository>:$CI_COMMIT_SHA
        #image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        image: ivan1845/flask_app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer # или LoadBalancer в зависимости от среды
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: flask-app